# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'Library Data Workshops'
description:         'A list of library workshops related to data.'
url:                 http://ucsdlib.github.io/workshops/
baseurl:             'http://ucsdlib.github.io/workshops/'
paginate:            5

# About/contact
author:
  name:              Tim Dennis
  url:               https://twitter.com/jt14den
  email:             timdennis@ucsd.edu

# Custom vars
version:             1.0.0
