markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Data Work-shops
url: http://ucsdlib.github.io/workshops
description: A list of our workshops.
twitter: jt14den
