markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /posts/:title/
gems:
  - jekyll-sitemap
  - jekyll-mentions

name: Data Workshops
url: http://ucsdlib.github.io/workshops
description: A list of our workshops.
twitter: ucsdlibrary

# Enables/Disable future posts (posts with dates in the future) and drafts.  set using: True | False
future: True
